on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Setup OpenSCAD
        run: sudo snap install openscad-nightly
      - name: Build
        run: make all
    