on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - run: sudo snap install openscad-nightly
      - run: make all
      - uses: actions/upload-artifact@v4
        with:
            name: deckbox
            path: dist
    